import type { Message } from '../types.js';
import type { LLMProvider } from '../providers/base.js';

/**
 * Condenses the tail end of the conversation history to protect the context window from token bloat.
 * Replaces older messages with a dense summary generated by the LLM.
 * 
 * @param messages The full conversational history string
 * @param provider The LLM provider to run the compression
 * @param threshold The length threshold to trigger compression
 * @returns A new array of messages with older messages condensed, or the original if below threshold
 */
export async function compressConversationHistory(messages: Message[], provider: LLMProvider, threshold: number = 20, onStatus?: (msg: string) => void): Promise<Message[]> {
    // Leave the system prompt alone, and only compress if we exceed the threshold
    if (messages.length <= threshold) {
        return messages;
    }

    // Identify system prompt vs conversational history
    let systemPrompt: Message | undefined;
    let conversationBuffer = messages;

    if (messages[0].role === 'system') {
        systemPrompt = messages[0];
        conversationBuffer = messages.slice(1);
    }

    // Keep the last N messages perfectly intact for immediate context
    const RECENT_MESSAGES_TO_KEEP = 6;
    if (conversationBuffer.length <= RECENT_MESSAGES_TO_KEEP + 2) {
        return messages; // Not enough buffer to meaningfully compress
    }

    const messagesToCompress = conversationBuffer.slice(0, conversationBuffer.length - RECENT_MESSAGES_TO_KEEP);
    const recentMessages = conversationBuffer.slice(conversationBuffer.length - RECENT_MESSAGES_TO_KEEP);

    // Format the older messages for the LLM
    const compressionPrompt = `
You are an expert agent memory manager. I am going to give you a transcript of an ongoing coding session below.
Your job is to condense this older history into a DENSE, objective summary.

Instructions:
1. Summarize the user's core intent and overarching goals.
2. Summarize the specific technical steps that have been successfully taken so far (files modified, decisions made).
3. Do NOT include raw code snippets, full file contents, or verbose outputs. Focus entirely on narrative progress.
4. Output your summary directly as plain text. Do not use pleasantries.

<transcript>
${JSON.stringify(messagesToCompress, null, 2)}
</transcript>
    `;

    try {
        const statusMsg = `[Auto-Compacting History] Condensing ${messagesToCompress.length} old messages...`;
        if (onStatus) { onStatus(statusMsg); } else { process.stderr.write(statusMsg + '\n'); }
        const stream = provider.chat([
            { role: 'system', content: 'You are a highly efficient memory compression engine.' },
            { role: 'user', content: compressionPrompt }
        ]);

        let summary = '';
        for await (const chunk of stream) {
            if (chunk.type === 'text') summary += chunk.text;
        }

        const compressedMessage: Message = {
            role: 'user',
            content: `[History Compacted — the following summarizes earlier turns]\n${summary}`
        };

        const newHistory: Message[] = [];
        if (systemPrompt) newHistory.push(systemPrompt);
        newHistory.push(compressedMessage);

        // Ensure valid message ordering: after the summary (user), the next message
        // must be assistant. If recentMessages starts with tool/user, we need to
        // ensure we don't create an invalid user→user or user→tool sequence.
        // Find the first valid continuation point.
        let startIdx = 0;
        if (recentMessages.length > 0 && recentMessages[0].role === 'tool') {
            // Skip orphaned tool results that lost their assistant (tool_call) parent
            while (startIdx < recentMessages.length && recentMessages[startIdx].role === 'tool') {
                startIdx++;
            }
        }
        // Skip consecutive user messages right after our summary (would create user→user)
        while (startIdx < recentMessages.length && recentMessages[startIdx].role === 'user') {
            startIdx++;
        }

        newHistory.push(...recentMessages.slice(startIdx));

        return newHistory;
    } catch (e) {
        const errMsg = `[Auto-Compacting] Failed to compress history: ${e}`;
        if (onStatus) { onStatus(errMsg); } else { process.stderr.write(errMsg + '\n'); }
        // Fallback to naive slice if API call fails
        const newHistory = [];
        if (systemPrompt) newHistory.push(systemPrompt);
        newHistory.push(...recentMessages);
        return newHistory;
    }
}
